name: Bai Tap 2
on:
  push:
    branches: [ BaiTap2 ]
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: current workking directory
        run: pwd
      - name: list file
        run: ls -la
      - name: list all env
        run: printenv
      - name: show version
        run: lsb_release -a
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-east-1
