name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Name
        run: export NAME = "Nguyen Dang Hung"
      - name: Date
        run: export DATE = date
      - name: print
        run: echo "Xin chao " $NAME "Hom nay la thu:" $DATE
